title: NLP/LLM, Okoth67
description: Exploring the fascinating world of Natural Language Processing and Large Language Models. Join me as I document my learning journey, share insights from NLP research, and showcase hands-on projects with transformers, fine-tuning, and AI applications.
baseurl: ""
url: "https://Okoth67.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
